CREATE DATABASE LogBook;

GO

USE LogBook;

GO

CREATE TABLE User(
	UserID INT IDENTITY(1,1) PRIMARY KEY,
	Email VARCHAR(100) UNIQUE,
	UserName VARCHAR(50) NOT NULL,
);
GO

CREATE TABLE Topic(
	TopicID INT IDENTITY(1,1) PRIMARY KEY, 
	Theme VARCHAR(100) NOT NULL,
	Content VARCHAR(500) NOT NULL,
);
GO

CREATE TABLE Session(
	SessionID INT IDENTITY(1,1) PRIMARY KEY,
	TopicID INT NOT NULL,
	SesionDate DATETIME DEFAULT GETDATE(),
	DurationMinutes INT,
	SesionDescription VARCHAR (500),
	CONSTRAINT FK_Session_Topic FOREIGN KEY (TopicID)
		REFERENCES Topic(TopicID)
);
GO

CREATE TABLE Exercise(
	ExerciseID INT IDENTITY(1,1) PRIMARY KEY,
	TopicID INT NOT NULL,
	ExerciseDescription VARCHAR(150),
	Result VARCHAR(500),
	CONSTRAINT FK_Exercise_Topic FOREIGN KEY (TopicID)
		REFERENCES Topic(TopicID)
);
GO

CREATE TABLE Question(
	QuestionID INT IDENTITY(1,1) PRIMARY KEY,
	TopicID INT NOT NULL,
	QuestionStatement VARCHAR(150), 
	QuestionDate DATETIME DEFAULT GETDATE(),
	AnswerDate DATETIME DEFAULT GETDATE(),
	Answer VARCHAR(600),
	CONSTRAINT FK_Question_Topic FOREIGN KEY (TopicID)
		REFERENCES Topic(TopicID)
);
GO
