CREATE DATABASE LogBook;

GO

USE LogBook;

GO

CREATE TABLE Topic(
	TopicID INT IDENTITY(1,1) PRIMARY KEY, 
	Theme NVARCHAR(100) NOT NULL,
	Content NVARCHAR(MAX) NOT NULL,
);
GO

CREATE TABLE Session(
	SessionID INT IDENTITY(1,1) PRIMARY KEY,
	TopicID INT NOT NULL,
	SesionDate DATETIME NOT NULL DEFAULT GETDATE(),
	DurationMinutes INT,
	SesionDescription NVARCHAR (MAX),
	CONSTRAINT FK_Session_Topic FOREIGN KEY (TopicID)
		REFERENCES Topic(TopicID)
);
GO

CREATE TABLE Exercise(
	ExerciseID INT IDENTITY(1,1) PRIMARY KEY,
	TopicID INT NOT NULL,
	ExerciseDescription NVARCHAR(MAX),
	Result NVARCHAR(MAX),
	CONSTRAINT FK_Exercise_Topic FOREIGN KEY (TopicID)
		REFERENCES Topic(TopicID)
);
GO

CREATE TABLE Question(
	QuestionID INT IDENTITY(1,1) PRIMARY KEY,
	TopicID INT NOT NULL,
	QuestionStatement NVARCHAR(MAX), 
	QuestionDate DATETIME NOT NULL DEFAULT GETDATE(),
	AnswerDate DATETIME NOT NULL DEFAULT GETDATE(),
	Answer NVARCHAR(MAX),
	CONSTRAINT FK_Question_Topic FOREIGN KEY (TopicID)
		REFERENCES Topic(TopicID)
);
GO
