CREATE TABLE Question(
	QuestionID INT IDENTITY(1,1) PRIMARY KEY,
	TopicID INT NOT NULL,
	QuestionStatement VARCHAR(150), 
	QuestionDate DATETIME DEFAULT GETDATE(),
	AnswerDate DATETIME DEFAULT GETDATE(),
	Answer VARCHAR(600),
	CreateUser VARCHAR(50) CONSTRAINT DF_CreateUser DEFAULT ORIGINAL_LOGIN(),
    CreateDate DATETIME CONSTRAINT DF_CreateDate DEFAULT GETDATE(),
    LastUpdateUser VARCHAR(50) CONSTRAINT DF_LastUpdateUser DEFAULT ORIGINAL_LOGIN(),
    LastUpdateDate DATETIME CONSTRAINT DF_LastUpdateDate DEFAULT GETDATE(),
	CONSTRAINT FK_Question_Topic FOREIGN KEY (TopicID)
		REFERENCES Topic(TopicID)
);
