CREATE TABLE User(
	UserID INT IDENTITY(1,1) PRIMARY KEY,
	Email VARCHAR(100) UNIQUE,
	UserName VARCHAR(50) NOT NULL,
	CreateUser VARCHAR(50) CONSTRAINT DF_CreateUser DEFAULT ORIGINAL_LOGIN(),
    CreateDate DATETIME CONSTRAINT DF_CreateDate DEFAULT GETDATE(),
    LastUpdateUser VARCHAR(50) CONSTRAINT DF_LastUpdateUser DEFAULT ORIGINAL_LOGIN(),
    LastUpdateDate DATETIME CONSTRAINT DF_LastUpdateDate DEFAULT GETDATE()
);
